# Generated by scripts/sync-kind-schemas.mjs from schema/v1/kinds. Do not edit by hand.
import json

KIND_SCHEMAS = json.loads(r'''{
  "guideline": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://hn2.github.io/uacp/schema/v1/kinds/guideline",
    "title": "UACP Guideline Body",
    "description": "Body schema for the guideline artifact kind — a soft instruction or style preference.",
    "type": "object",
    "properties": {
      "title": {
        "type": "string",
        "minLength": 1,
        "maxLength": 128
      },
      "instruction": {
        "type": "string",
        "minLength": 1,
        "maxLength": 2000
      },
      "priority": {
        "type": "integer",
        "minimum": 1,
        "maximum": 10,
        "default": 5
      }
    },
    "required": [
      "title",
      "instruction"
    ],
    "additionalProperties": false
  },
  "memory": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://hn2.github.io/uacp/schema/v1/kinds/memory",
    "title": "UACP Memory Body",
    "description": "Body schema for the memory artifact kind — a single persistent fact, preference, or piece of recalled context about a user.",
    "type": "object",
    "properties": {
      "content": {
        "type": "string",
        "minLength": 1,
        "maxLength": 2000
      },
      "category": {
        "type": "string",
        "pattern": "^(personal|professional|preference|health|relationship|financial|[a-z0-9][a-z0-9-]*/[a-z0-9][a-z0-9-]*)$"
      },
      "confidence": {
        "type": "number",
        "minimum": 0,
        "maximum": 1,
        "default": 1
      },
      "source": {
        "type": "string",
        "maxLength": 256
      },
      "expires_at": {
        "type": [
          "string",
          "null"
        ],
        "format": "date-time",
        "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{3})?Z$"
      },
      "lifecycle": {
        "type": "object",
        "properties": {
          "action": {
            "enum": [
              "create",
              "confirm",
              "update",
              "supersede",
              "tombstone",
              "expire",
              "rollback"
            ]
          },
          "status": {
            "enum": [
              "active",
              "superseded",
              "tombstoned",
              "expired"
            ]
          },
          "revision": {
            "type": "integer",
            "minimum": 1
          },
          "previous_revision": {
            "$ref": "#/$defs/revisionReference"
          }
        },
        "required": [
          "action",
          "status",
          "revision"
        ],
        "additionalProperties": false
      },
      "supersedes": {
        "type": "array",
        "minItems": 1,
        "maxItems": 32,
        "items": {
          "$ref": "#/$defs/revisionReference"
        }
      },
      "derived_from": {
        "type": "array",
        "minItems": 1,
        "maxItems": 32,
        "items": {
          "$ref": "#/$defs/revisionReference"
        }
      },
      "provenance": {
        "type": "array",
        "minItems": 1,
        "maxItems": 64,
        "items": {
          "$ref": "#/$defs/sourceEvidence"
        }
      },
      "consent": {
        "enum": [
          "not_required",
          "explicit",
          "withdrawn"
        ]
      },
      "topics": {
        "type": "array",
        "maxItems": 16,
        "uniqueItems": true,
        "items": {
          "type": "string",
          "minLength": 1,
          "maxLength": 64,
          "pattern": "^[a-z0-9][a-z0-9-]*(/[a-z0-9][a-z0-9-]*)?$"
        }
      },
      "metadata": {
        "type": "array",
        "maxItems": 32,
        "items": {
          "$ref": "#/$defs/typedMetadata"
        }
      },
      "profile_link": {
        "$ref": "#/$defs/profileLink"
      }
    },
    "required": [
      "content"
    ],
    "additionalProperties": false,
    "$defs": {
      "revisionReference": {
        "type": "object",
        "properties": {
          "memory_id": {
            "type": "string",
            "minLength": 1,
            "maxLength": 256
          },
          "revision": {
            "type": "integer",
            "minimum": 1
          }
        },
        "required": [
          "memory_id",
          "revision"
        ],
        "additionalProperties": false
      },
      "sourceEvidence": {
        "type": "object",
        "properties": {
          "source_type": {
            "enum": [
              "vendor",
              "tool",
              "session",
              "event",
              "other"
            ]
          },
          "identifier": {
            "type": "string",
            "minLength": 1,
            "maxLength": 256
          },
          "content_hash": {
            "type": "string",
            "pattern": "^sha256:[a-f0-9]{64}$"
          },
          "observed_at": {
            "type": "string",
            "format": "date-time",
            "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{3})?Z$"
          }
        },
        "required": [
          "source_type",
          "identifier"
        ],
        "additionalProperties": false
      },
      "typedMetadata": {
        "type": "object",
        "properties": {
          "key": {
            "type": "string",
            "minLength": 1,
            "maxLength": 64,
            "pattern": "^(?:[a-z0-9][a-z0-9_-]*|[a-z0-9][a-z0-9-]*/[a-z0-9][a-z0-9-]*)$"
          },
          "type": {
            "enum": [
              "string",
              "number",
              "boolean",
              "date",
              "null"
            ]
          },
          "value": {}
        },
        "required": [
          "key",
          "type",
          "value"
        ],
        "additionalProperties": false,
        "allOf": [
          {
            "if": {
              "properties": {
                "type": {
                  "const": "string"
                }
              }
            },
            "then": {
              "properties": {
                "value": {
                  "type": "string",
                  "maxLength": 1024
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "number"
                }
              }
            },
            "then": {
              "properties": {
                "value": {
                  "type": "number"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "boolean"
                }
              }
            },
            "then": {
              "properties": {
                "value": {
                  "type": "boolean"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "date"
                }
              }
            },
            "then": {
              "properties": {
                "value": {
                  "type": "string",
                  "format": "date-time",
                  "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{3})?Z$"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "null"
                }
              }
            },
            "then": {
              "properties": {
                "value": {
                  "type": "null"
                }
              }
            }
          }
        ]
      },
      "profileLink": {
        "type": "object",
        "properties": {
          "schema_id": {
            "type": "string",
            "minLength": 1,
            "maxLength": 128,
            "pattern": "^[a-z0-9][a-z0-9-]*(/[a-z0-9][a-z0-9-]*)?$"
          },
          "schema_version": {
            "type": "integer",
            "minimum": 1
          },
          "field": {
            "type": "string",
            "minLength": 1,
            "maxLength": 128,
            "pattern": "^(?:[A-Za-z0-9][A-Za-z0-9_.-]*|/(?:[A-Za-z0-9._~-]|~[01])+(?:/(?:[A-Za-z0-9._~-]|~[01])+)*)$"
          },
          "conflict": {
            "enum": [
              "none",
              "unresolved",
              "resolved"
            ]
          }
        },
        "required": [
          "schema_id",
          "schema_version",
          "field"
        ],
        "additionalProperties": false
      }
    }
  },
  "pack": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://hn2.github.io/uacp/schema/v1/kinds/pack",
    "title": "UACP Pack Body",
    "description": "Body schema for the pack artifact kind — a named, curated collection of related artifacts.",
    "type": "object",
    "properties": {
      "title": {
        "type": "string",
        "minLength": 1,
        "maxLength": 128
      },
      "description": {
        "type": "string",
        "maxLength": 512
      },
      "artifact_refs": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "kind": {
              "type": "string",
              "minLength": 1
            },
            "id": {
              "type": "string"
            },
            "slug": {
              "type": "string"
            }
          },
          "required": [
            "kind"
          ],
          "additionalProperties": false
        },
        "minItems": 1,
        "maxItems": 50
      },
      "tags": {
        "type": "array",
        "items": {
          "type": "string",
          "maxLength": 64
        },
        "maxItems": 10
      }
    },
    "required": [
      "title",
      "description",
      "artifact_refs"
    ],
    "additionalProperties": false
  },
  "persona": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://hn2.github.io/uacp/schema/v1/kinds/persona",
    "title": "UACP Persona Body",
    "description": "Body schema for the persona artifact kind — an AI identity, voice, and behavioral configuration.",
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "minLength": 1,
        "maxLength": 64
      },
      "description": {
        "type": "string",
        "minLength": 1,
        "maxLength": 512
      },
      "system_prompt": {
        "type": "string",
        "minLength": 1,
        "maxLength": 8000
      },
      "voice_style": {
        "type": "string",
        "maxLength": 256
      },
      "avatar_url": {
        "type": "string",
        "maxLength": 2048,
        "format": "uri"
      },
      "capabilities": {
        "type": "array",
        "items": {
          "type": "string",
          "maxLength": 64
        },
        "maxItems": 20
      },
      "restrictions": {
        "type": "array",
        "items": {
          "type": "string",
          "maxLength": 64
        },
        "maxItems": 20
      }
    },
    "required": [
      "name",
      "description",
      "system_prompt"
    ],
    "additionalProperties": false
  },
  "playbook": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://hn2.github.io/uacp/schema/v1/kinds/playbook",
    "title": "UACP Playbook Body",
    "description": "Body schema for the playbook artifact kind — a sequenced, multi-step workflow of instructions or actions.",
    "type": "object",
    "properties": {
      "title": {
        "type": "string",
        "minLength": 1,
        "maxLength": 128
      },
      "description": {
        "type": "string",
        "maxLength": 512
      },
      "steps": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "step": {
              "type": "integer",
              "minimum": 1
            },
            "title": {
              "type": "string",
              "minLength": 1,
              "maxLength": 128
            },
            "instruction": {
              "type": "string",
              "minLength": 1,
              "maxLength": 2000
            },
            "on_complete": {
              "type": "string",
              "maxLength": 512
            }
          },
          "required": [
            "step",
            "title",
            "instruction"
          ],
          "additionalProperties": false
        },
        "minItems": 1,
        "maxItems": 50
      },
      "tags": {
        "type": "array",
        "items": {
          "type": "string",
          "maxLength": 64
        },
        "maxItems": 10
      }
    },
    "required": [
      "title",
      "description",
      "steps"
    ],
    "additionalProperties": false
  },
  "policy": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://hn2.github.io/uacp/schema/v1/kinds/policy",
    "title": "UACP Policy Body",
    "description": "Body schema for the policy artifact kind — a hard constraint that an AI system must enforce.",
    "type": "object",
    "properties": {
      "title": {
        "type": "string",
        "minLength": 1,
        "maxLength": 128
      },
      "rule": {
        "type": "string",
        "minLength": 1,
        "maxLength": 2000
      },
      "scope": {
        "type": "string",
        "minLength": 1
      },
      "enforcement": {
        "type": "string",
        "enum": [
          "hard",
          "soft"
        ]
      },
      "created_by": {
        "type": "string",
        "enum": [
          "user",
          "operator"
        ]
      },
      "tags": {
        "type": "array",
        "items": {
          "type": "string",
          "maxLength": 64
        },
        "maxItems": 10
      }
    },
    "required": [
      "title",
      "rule",
      "scope",
      "enforcement",
      "created_by"
    ],
    "additionalProperties": false
  },
  "redaction-pattern": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://hn2.github.io/uacp/schema/v1/kinds/redaction-pattern",
    "title": "UACP Redaction Pattern Body",
    "description": "Body schema for the redaction-pattern artifact kind — a pattern used to detect and redact sensitive content.",
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "minLength": 1,
        "maxLength": 128
      },
      "pattern": {
        "type": "string",
        "minLength": 1,
        "maxLength": 4096
      },
      "replacement": {
        "type": "string",
        "maxLength": 256,
        "default": "[REDACTED]"
      },
      "pattern_type": {
        "type": "string",
        "enum": [
          "regex",
          "glob"
        ]
      },
      "scope": {
        "type": "string",
        "enum": [
          "outbound",
          "inbound",
          "both"
        ]
      },
      "is_builtin": {
        "type": "boolean"
      }
    },
    "required": [
      "name",
      "pattern",
      "pattern_type",
      "scope",
      "is_builtin"
    ],
    "additionalProperties": false
  },
  "source": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://hn2.github.io/uacp/schema/v1/kinds/source",
    "title": "UACP Source Body",
    "description": "Body schema for the source artifact kind — a citation or reference material.",
    "type": "object",
    "properties": {
      "title": {
        "type": "string",
        "minLength": 1,
        "maxLength": 256
      },
      "url": {
        "type": "string",
        "maxLength": 2048,
        "format": "uri"
      },
      "type": {
        "type": "string",
        "enum": [
          "webpage",
          "document",
          "feed",
          "api"
        ]
      },
      "last_fetched": {
        "type": "string",
        "format": "date-time",
        "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{3})?Z$"
      },
      "content_hash": {
        "type": "string"
      }
    },
    "required": [
      "title",
      "type"
    ],
    "additionalProperties": false
  },
  "theme": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://hn2.github.io/uacp/schema/v1/kinds/theme",
    "title": "UACP Theme Body",
    "description": "Body schema for the theme artifact kind — visual or tonal configuration for an AI tool's interface.",
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "minLength": 1,
        "maxLength": 64
      },
      "mode": {
        "type": "string",
        "enum": [
          "light",
          "dark",
          "system"
        ]
      },
      "accent_color": {
        "type": "string",
        "pattern": "^#[0-9a-fA-F]{3,6}$"
      },
      "font_family": {
        "type": "string",
        "maxLength": 256
      },
      "density": {
        "type": "string",
        "enum": [
          "compact",
          "normal",
          "spacious"
        ],
        "default": "normal"
      },
      "custom_css": {
        "type": "string",
        "maxLength": 16384
      }
    },
    "required": [
      "name",
      "mode"
    ],
    "additionalProperties": false
  },
  "trace": {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://hn2.github.io/uacp/schema/v1/kinds/trace",
    "title": "UACP Trace Body",
    "description": "Body schema for the trace artifact kind — operational telemetry for a single AI tool invocation.",
    "type": "object",
    "properties": {
      "tool": {
        "type": "string",
        "minLength": 1,
        "maxLength": 128
      },
      "command": {
        "type": "string",
        "maxLength": 256
      },
      "model": {
        "type": [
          "string",
          "null"
        ],
        "maxLength": 128
      },
      "duration_ms": {
        "type": "integer",
        "minimum": 0
      },
      "tokens_in": {
        "type": [
          "integer",
          "null"
        ],
        "minimum": 0
      },
      "tokens_out": {
        "type": [
          "integer",
          "null"
        ],
        "minimum": 0
      },
      "privacy_mode": {
        "type": "string",
        "enum": [
          "smart",
          "private",
          "incognito"
        ]
      },
      "session_id": {
        "type": "string",
        "maxLength": 128
      }
    },
    "required": [
      "tool",
      "duration_ms",
      "privacy_mode"
    ],
    "additionalProperties": false
  }
}''')
